# Generated by Django 3.1.2 on 2020-10-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201024_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.CharField(default='blya', max_length=20),
        ),
    ]
