version: "3.9"
services:
  web:
    build: .
    command: gunicorn brieflyMain.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=briefly
      - POSTGRES_PASSWORD=briefly
      - POSTGRES_DB=briefly

volumes:
  postgres_data:
